name: lagn_app
publish_to: 'none'
description: Marathi Marriage Form — WhatsApp API Ready
version: 1.1.0+2
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  path: ^1.9.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  http: ^1.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/
